# Generated by Django 4.2.26 on 2025-11-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonData',
            fields=[
                ('carbon_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('dtc_mg_c_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Растворенный углерод (мгC/л)')),
                ('dic_mg_c_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Неорганический углерод (мгC/л)')),
                ('doc_mg_c_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Органический углерод (мгC/л)')),
                ('tss_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Взвесь общая (мг/л)')),
                ('poc_mg_c_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Взвешенный углерод (мгС/м³)')),
            ],
            options={
                'verbose_name': 'Данные по углероду',
                'verbose_name_plural': 'Данные по углероду',
                'db_table': 'carbon_data',
            },
        ),
        migrations.CreateModel(
            name='CTDData',
            fields=[
                ('ctd_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('pressure_dbar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Давление (dBar)')),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура (°C)')),
                ('cond_ms_cm', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Электропроводность (мС/см)')),
                ('salinity_psu', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Соленость (PSU)')),
                ('do_ml_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кислород (мл/л), по CTD')),
                ('do_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кислород (мг/л), по CTD')),
                ('do_sat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Насыщение кислородом (%), по CTD')),
                ('chl_a_ug_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Хлорофилл-а (µg/L)')),
                ('turbidity_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Мутность (NTU), по CTD')),
                ('cdom_ppb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CDOM (ppb)')),
                ('sigma_kg_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Плотность (kg/m³)')),
                ('measured_depth_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Измеренная глубина (м)')),
            ],
            options={
                'verbose_name': 'Данные CTD',
                'verbose_name_plural': 'Данные CTD',
                'db_table': 'ctd_data',
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('expedition_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата начала экспедиции')),
                ('end_date', models.DateField(verbose_name='Дата окончания экспедиции')),
                ('platform', models.CharField(max_length=200, verbose_name='Название судна/платформы')),
                ('area', models.CharField(max_length=300, verbose_name='Район работ')),
            ],
            options={
                'verbose_name': 'Экспедиция',
                'verbose_name_plural': 'Экспедиции',
                'db_table': 'expeditions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('probe_id', models.AutoField(primary_key=True, serialize=False)),
                ('probe_name', models.CharField(max_length=100, verbose_name='Название/модель зонда')),
                ('description', models.TextField(blank=True, verbose_name='Описание характеристик')),
            ],
            options={
                'verbose_name': 'Зонд',
                'verbose_name_plural': 'Зонды',
                'db_table': 'probes',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=200, verbose_name='Название станции')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время станции')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('bottom_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Глубина дна (м)')),
                ('secchi_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Прозрачность по диску Секки (м)')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='oceanography.expedition', verbose_name='Экспедиция')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'db_table': 'stations',
                'ordering': ['expedition', 'datetime'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Дата и время отбора пробы')),
                ('sampling_depth', models.CharField(max_length=50, verbose_name='Горизонт отбора')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='oceanography.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Проба',
                'verbose_name_plural': 'Пробы',
                'db_table': 'samples',
                'ordering': ['station__expedition', 'station', 'datetime'],
            },
        ),
        migrations.CreateModel(
            name='PigmentsData',
            fields=[
                ('pigments_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('chl_a_mg_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Хлорофилл-а (мг/м³)')),
                ('chl_a_pheo_mg_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Хлорофилл-а+феофитин (мг/м³)')),
                ('chl_a_tri_mg_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Хлорофилл-а (трихроматический) (мг/м³)')),
                ('total_chl_mg_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Суммарный хлорофилл (мг/м³)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigments_data', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Данные по пигментам',
                'verbose_name_plural': 'Данные по пигментам',
                'db_table': 'pigments_data',
            },
        ),
        migrations.CreateModel(
            name='PHMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_meter', models.CharField(max_length=100, verbose_name='Название/модель прибора')),
                ('ph_value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Значение pH')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_measurements', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Измерение pH',
                'verbose_name_plural': 'Измерения pH',
                'db_table': 'ph_measurements',
            },
        ),
        migrations.CreateModel(
            name='OxymetrData',
            fields=[
                ('oxymetr_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('do_mg_l_oxy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кислород (мг/л), по оксиметру')),
                ('do_sat_percent_oxy', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Насыщение кислородом (%), по оксиметру')),
                ('turbidity_ntu_oxy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Мутность (NTU), по оксиметру')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxymetr_data', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Данные оксиметра',
                'verbose_name_plural': 'Данные оксиметра',
                'db_table': 'oxymetr_data',
            },
        ),
        migrations.CreateModel(
            name='NutrientsData',
            fields=[
                ('nutrients_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('no2_mg_n_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Нитриты (мгN/л)')),
                ('no3_mg_n_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Нитраты (мгN/л)')),
                ('nh4_mg_n_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Аммоний (мгN/л)')),
                ('po4_mg_p_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Фосфаты (мгP/л)')),
                ('si_mg_si_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Кремний (мгSi/л)')),
                ('dtotn_mg_n_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Растворенный азот (мгN/л)')),
                ('totn_mg_n_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Валовой азот (мгN/л)')),
                ('dtotp_mg_p_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Растворенный фосфор (мгP/л)')),
                ('totp_mg_p_l', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Валовой фосфор (мгP/л)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients_data', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Данные по биогенам',
                'verbose_name_plural': 'Данные по биогенам',
                'db_table': 'nutrients_data',
            },
        ),
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('meteo_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_air_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура воздуха (°C)')),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Влажность (%)')),
                ('wind_speed_m_s', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Скорость ветра (м/с)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True, verbose_name='Направление ветра')),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Атмосферное давление (гПа)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_data', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Метеоданные',
                'verbose_name_plural': 'Метеоданные',
                'db_table': 'meteo_data',
            },
        ),
        migrations.CreateModel(
            name='IonicCompositionData',
            fields=[
                ('ionic_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Хлориды (мг-экв/л)')),
                ('cl_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Хлориды (мг/л)')),
                ('hco3_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Гидрокарбонаты (мг-экв/л)')),
                ('hco3_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Гидрокарбонаты (мг/л)')),
                ('so4_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Сульфаты (мг-экв/л)')),
                ('so4_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Сульфаты (мг/л)')),
                ('hardness_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Жесткость (мг-экв/л)')),
                ('ca_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Кальций (мг-экв/л)')),
                ('ca_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Кальций (мг/л)')),
                ('mg_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Магний (мг-экв/л)')),
                ('mg_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Магний (мг/л)')),
                ('na_k_meq_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Натрий+Калий (мг-экв/л)')),
                ('na_k_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Натрий+Калий (мг/л)')),
                ('mineralization_mg_l', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Общая минерализация (мг/л)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ionic_data', to='oceanography.sample', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Данные по ионному составу',
                'verbose_name_plural': 'Данные по ионному составу',
                'db_table': 'ionic_composition_data',
            },
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['start_date'], name='expeditions_start_d_bc25a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['platform'], name='expeditions_platfor_aabe1d_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['area'], name='expeditions_area_adaa45_idx'),
        ),
        migrations.AddField(
            model_name='ctddata',
            name='probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctd_measurements', to='oceanography.probe', verbose_name='Зонд'),
        ),
        migrations.AddField(
            model_name='ctddata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctd_data', to='oceanography.sample', verbose_name='Проба'),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_data', to='oceanography.sample', verbose_name='Проба'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['expedition', 'datetime'], name='stations_expedit_5ed898_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='stations_latitud_2690e9_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['datetime'], name='stations_datetim_72530f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('expedition', 'datetime')},
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['station', 'datetime'], name='samples_station_41dcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['datetime'], name='samples_datetim_8d97ba_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sampling_depth'], name='samples_samplin_3c73e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ctddata',
            index=models.Index(fields=['sample', 'probe'], name='ctd_data_sample__d02d8b_idx'),
        ),
    ]
