# Generated by Django 4.2.26 on 2025-11-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phmeasurement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_measurements', to='oceanography.sample', verbose_name='Проба'),
        ),
    ]
