# Generated by Django 4.2.26 on 2025-11-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteodata',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Направление ветра'),
        ),
    ]
