# Generated by Django 4.2.26 on 2025-11-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0002_alter_meteodata_wind_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='Время начала профилирования')),
                ('end_datetime', models.DateTimeField(verbose_name='Время окончания профилирования')),
                ('max_depth', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Максимальная глубина профиля (м)')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='ctd_profiles/', verbose_name='Файл с данными')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии к профилю')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctd_profiles', to='oceanography.probe', verbose_name='Зонд')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctd_profiles', to='oceanography.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'CTD профиль',
                'verbose_name_plural': 'CTD профили',
                'db_table': 'ctd_profiles',
                'ordering': ['station', 'start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CTDMeasurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Дата и время измерения')),
                ('depth_m', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Глубина (м)')),
                ('pressure_dbar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Давление (dBar)')),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура (°C)')),
                ('cond_ms_cm', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Электропроводность (мС/см)')),
                ('salinity_psu', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Соленость (PSU)')),
                ('do_ml_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кислород (мл/л)')),
                ('do_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кислород (мг/л)')),
                ('do_sat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Насыщение кислородом (%)')),
                ('chl_a_ug_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Хлорофилл-а (µg/L)')),
                ('turbidity_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Мутность (NTU)')),
                ('cdom_ppb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CDOM (ppb)')),
                ('sigma_kg_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Плотность (kg/m³)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='oceanography.ctdprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'CTD измерение',
                'verbose_name_plural': 'CTD измерения',
                'db_table': 'ctd_measurements',
                'ordering': ['profile', 'depth_m'],
            },
        ),
        migrations.AddIndex(
            model_name='ctdprofile',
            index=models.Index(fields=['station', 'start_datetime'], name='ctd_profile_station_7af1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ctdprofile',
            index=models.Index(fields=['start_datetime'], name='ctd_profile_start_d_bd1882_idx'),
        ),
        migrations.AddIndex(
            model_name='ctdmeasurement',
            index=models.Index(fields=['profile', 'depth_m'], name='ctd_measure_profile_2d3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='ctdmeasurement',
            index=models.Index(fields=['profile', 'datetime'], name='ctd_measure_profile_7dd9b6_idx'),
        ),
    ]
