# Generated by Django 4.2.26 on 2025-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0002_alter_phmeasurement_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания экспедиции'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала экспедиции'),
        ),
    ]
